GET http://localhost:8081/users

#####

GET http://localhost:8081/users/68b6f40d2d104dda1db278bd/posts

#####

POST http://localhost:8081/users
Content-Type: application/json

{
    "name": "Aparecida Emilly dos Santos",
    "email": "aparecida.emilly.dossantos@cfaraujo.eng.br"
}

####

DELETE http://localhost:8081/users/68b636e3754f40bdde6baa29

####

PUT http://localhost:8081/users/68b63a21189f2ed2a0533200
Content-Type: application/json

{
    "name": "Aparecida E. dos Santos",
    "email": "aparecida.emilly.dossantos@cfaraujo.eng.br"
}